+incdir+/home/shc/projects/secure-soc/cva6/core/include
+incdir+/home/shc/projects/secure-soc/cva6/vendor/pulp-platform/common_cells/include
+incdir+/home/shc/projects/secure-soc/cva6/common/local/util
+incdir+/home/shc/projects/secure-soc/cva6/corev_apu/register_interface/include
+incdir+/home/shc/projects/secure-soc/axi/include
+incdir+/home/shc/projects/secure-soc/obi/include
/home/shc/projects/secure-soc/vivado/cva_soc_zc706/cva_soc_zc706.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.dcp
/home/shc/projects/secure-soc/rtl/src/peripherals/dram/ddr3_core.v
/home/shc/projects/secure-soc/rtl/src/peripherals/dram/ddr3_dfi_seq.v
/home/shc/projects/secure-soc/cva6/vendor/pulp-platform/fpga-support/rtl/AsyncDpRam.sv
/home/shc/projects/secure-soc/cva6/vendor/pulp-platform/fpga-support/rtl/AsyncThreePortRam.sv
/home/shc/projects/secure-soc/cva6/vendor/pulp-platform/fpga-support/rtl/SyncDpRam.sv
/home/shc/projects/secure-soc/cva6/vendor/pulp-platform/fpga-support/rtl/SyncDpRam_ind_r_w.sv
/home/shc/projects/secure-soc/cva6/vendor/pulp-platform/fpga-support/rtl/SyncSpRam.sv
/home/shc/projects/secure-soc/cva6/vendor/pulp-platform/fpga-support/rtl/SyncSpRamBeNx32.sv
/home/shc/projects/secure-soc/cva6/vendor/pulp-platform/fpga-support/rtl/SyncSpRamBeNx64.sv
/home/shc/projects/secure-soc/cva6/vendor/pulp-platform/fpga-support/rtl/SyncThreePortRam.sv
/home/shc/projects/secure-soc/cva6/core/include/config_pkg.sv
/home/shc/projects/secure-soc/rtl/src/config/custom_config.sv
/home/shc/projects/secure-soc/cva6/core/include/riscv_pkg.sv
/home/shc/projects/secure-soc/cva6/core/include/ariane_pkg.sv
/home/shc/projects/secure-soc/cva6/core/cvfpu/src/fpnew_pkg.sv
/home/shc/projects/secure-soc/cva6/core/cvfpu/src/common_cells/src/cf_math_pkg.sv
/home/shc/projects/secure-soc/cva6/vendor/pulp-platform/common_cells/src/cf_math_pkg.sv
/home/shc/projects/secure-soc/cva6/core/acc_dispatcher.sv
/home/shc/projects/secure-soc/cva6/vendor/pulp-platform/common_cells/src/addr_decode.sv
/home/shc/projects/secure-soc/cva6/core/alu.sv
/home/shc/projects/secure-soc/cva6/core/amo_buffer.sv
/home/shc/projects/secure-soc/axi/src/axi_pkg.sv
/home/shc/projects/secure-soc/cva6/vendor/pulp-platform/axi/src/axi_pkg.sv
/home/shc/projects/secure-soc/cva6/corev_apu/tb/ariane_axi_pkg.sv
/home/shc/projects/secure-soc/cva6/core/include/build_config_pkg.sv
/home/shc/projects/secure-soc/cva6/core/ariane_regfile_ff.sv
/home/shc/projects/secure-soc/cva6/core/ariane_regfile_fpga.sv
/home/shc/projects/secure-soc/cva6/core/include/wt_cache_pkg.sv
/home/shc/projects/secure-soc/obi/src/obi_pkg.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/axi_adapter.sv
/home/shc/projects/secure-soc/cva6/vendor/pulp-platform/axi/src/axi_atop_filter.sv
/home/shc/projects/secure-soc/cva6/vendor/pulp-platform/axi/src/axi_cut.sv
/home/shc/projects/secure-soc/cva6/vendor/pulp-platform/axi/src/axi_demux.sv
/home/shc/projects/secure-soc/axi/src/axi_demux_simple.sv
/home/shc/projects/secure-soc/cva6/vendor/pulp-platform/axi/src/axi_err_slv.sv
/home/shc/projects/secure-soc/cva6/vendor/pulp-platform/axi/src/axi_id_prepend.sv
/home/shc/projects/secure-soc/cva6/vendor/pulp-platform/axi/src/axi_multicut.sv
/home/shc/projects/secure-soc/cva6/vendor/pulp-platform/axi/src/axi_mux.sv
/home/shc/projects/secure-soc/cva6/corev_apu/src/axi_riscv_atomics/src/axi_res_tbl.sv
/home/shc/projects/secure-soc/cva6/corev_apu/src/axi_riscv_atomics/src/axi_riscv_amos.sv
/home/shc/projects/secure-soc/cva6/corev_apu/src/axi_riscv_atomics/src/axi_riscv_amos_alu.sv
/home/shc/projects/secure-soc/cva6/corev_apu/src/axi_riscv_atomics/src/axi_riscv_atomics.sv
/home/shc/projects/secure-soc/cva6/corev_apu/src/axi_riscv_atomics/src/axi_riscv_lrsc.sv
/home/shc/projects/secure-soc/cva6/core/axi_shim.sv
/home/shc/projects/secure-soc/axi/src/axi_to_detailed_mem.sv
/home/shc/projects/secure-soc/safety_island/future/axi_obi/src/axi_to_detailed_mem_user.sv
/home/shc/projects/secure-soc/safety_island/future/axi_obi/src/axi_to_obi.sv
/home/shc/projects/secure-soc/register_interface/src/axi_to_reg_v2.sv
/home/shc/projects/secure-soc/cva6/vendor/pulp-platform/axi/src/axi_xbar.sv
/home/shc/projects/secure-soc/axi/src/axi_xbar_unmuxed.sv
/home/shc/projects/secure-soc/cva6/core/frontend/bht.sv
/home/shc/projects/secure-soc/rtl/src/memory/bootrom.sv
/home/shc/projects/secure-soc/cva6/core/branch_unit.sv
/home/shc/projects/secure-soc/cva6/core/frontend/btb.sv
/home/shc/projects/secure-soc/cva6/core/include/std_cache_pkg.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/cache_ctrl.sv
/home/shc/projects/secure-soc/clint/src/clint_reg_pkg.sv
/home/shc/projects/secure-soc/clint/src/clint.sv
/home/shc/projects/secure-soc/clint/src/clint_reg_top.sv
/home/shc/projects/secure-soc/cva6/core/commit_stage.sv
/home/shc/projects/secure-soc/cva6/core/compressed_decoder.sv
/home/shc/projects/secure-soc/cva6/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/defs_div_sqrt_mvp.sv
/home/shc/projects/secure-soc/cva6/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/control_mvp.sv
/home/shc/projects/secure-soc/cva6/core/controller.sv
/home/shc/projects/secure-soc/cva6/vendor/pulp-platform/common_cells/src/counter.sv
/home/shc/projects/secure-soc/cva6/core/csr_buffer.sv
/home/shc/projects/secure-soc/cva6/core/csr_regfile.sv
/home/shc/projects/secure-soc/cva6/core/cva6.sv
/home/shc/projects/secure-soc/cva6/core/cva6_accel_first_pass_decoder_stub.sv
/home/shc/projects/secure-soc/cva6/core/cva6_fifo_v3.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_pkg.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/cva6_hpdcache_if_adapter.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/cva6_hpdcache_subsystem.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/cva6_hpdcache_subsystem_axi_arbiter.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride_pkg.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/cva6_hpdcache_wrapper.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/cva6_icache.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/cva6_icache_axi_wrapper.sv
/home/shc/projects/secure-soc/cva6/core/cva6_mmu/cva6_mmu.sv
/home/shc/projects/secure-soc/cva6/core/cva6_mmu/cva6_ptw.sv
/home/shc/projects/secure-soc/cva6/core/cva6_rvfi_probes.sv
/home/shc/projects/secure-soc/cva6/core/cva6_mmu/cva6_shared_tlb.sv
/home/shc/projects/secure-soc/cva6/core/cva6_mmu/cva6_tlb.sv
/home/shc/projects/secure-soc/cva6/core/cvxif_compressed_if_driver.sv
/home/shc/projects/secure-soc/cva6/core/cvxif_fu.sv
/home/shc/projects/secure-soc/cva6/core/cvxif_issue_register_commit_if_driver.sv
/home/shc/projects/secure-soc/rtl/src/peripherals/dram/ddr3_controller.sv
/home/shc/projects/secure-soc/rtl/src/peripherals/dram/ddr3_dfi_phy.sv
/home/shc/projects/secure-soc/cva6/core/decoder.sv
/home/shc/projects/secure-soc/cva6/vendor/pulp-platform/common_cells/src/delta_counter.sv
/home/shc/projects/secure-soc/cva6/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/div_sqrt_top_mvp.sv
/home/shc/projects/secure-soc/rtl/src/peripherals/dram/dram_controller_axi.sv
/home/shc/projects/secure-soc/rtl/src/peripherals/dram/dram_controller_wb.sv
/home/shc/projects/secure-soc/cva6/core/ex_stage.sv
/home/shc/projects/secure-soc/cva6/vendor/pulp-platform/common_cells/src/exp_backoff.sv
/home/shc/projects/secure-soc/cva6/vendor/pulp-platform/common_cells/src/fall_through_register.sv
/home/shc/projects/secure-soc/cva6/vendor/pulp-platform/common_cells/src/deprecated/fifo_v2.sv
/home/shc/projects/secure-soc/rtl/src/common_cells/fifo_v3.sv
/home/shc/projects/secure-soc/cva6/core/cvfpu/src/fpnew_cast_multi.sv
/home/shc/projects/secure-soc/cva6/core/cvfpu/src/fpnew_classifier.sv
/home/shc/projects/secure-soc/cva6/core/cvfpu/src/fpnew_divsqrt_multi.sv
/home/shc/projects/secure-soc/cva6/core/cvfpu/src/fpnew_fma.sv
/home/shc/projects/secure-soc/cva6/core/cvfpu/src/fpnew_fma_multi.sv
/home/shc/projects/secure-soc/cva6/core/cvfpu/src/fpnew_noncomp.sv
/home/shc/projects/secure-soc/cva6/core/cvfpu/src/fpnew_opgroup_block.sv
/home/shc/projects/secure-soc/cva6/core/cvfpu/src/fpnew_opgroup_fmt_slice.sv
/home/shc/projects/secure-soc/cva6/core/cvfpu/src/fpnew_opgroup_multifmt_slice.sv
/home/shc/projects/secure-soc/cva6/core/cvfpu/src/fpnew_rounding.sv
/home/shc/projects/secure-soc/cva6/core/cvfpu/src/fpnew_top.sv
/home/shc/projects/secure-soc/cva6/core/fpu_wrap.sv
/home/shc/projects/secure-soc/cva6/core/frontend/frontend.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_1hot_to_binary.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_amo.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_cmo.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_core_arbiter.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_ctrl.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_ctrl_pe.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_data_downsize.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_data_resize.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_data_upsize.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_decoder.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_demux.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_fifo_reg.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_flush.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_fxarb.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_lfsr.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_req_read_arbiter.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_req_write_arbiter.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_resp_demux.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_to_axi_read.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/utils/hpdcache_mem_to_axi_write.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_memctrl.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_miss_handler.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_mshr.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_mux.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_prio_1hot_encoder.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_regbank_wbyteenable_1rw.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_regbank_wmask_1rw.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_rrarb.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_rtab.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sram.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/common/macros/blackbox/hpdcache_sram_1rw.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sram_wbyteenable.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/common/macros/blackbox/hpdcache_sram_wbyteenable_1rw.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sram_wmask.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/common/macros/blackbox/hpdcache_sram_wmask_1rw.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/common/hpdcache_sync_buffer.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_uncached.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_victim_plru.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_victim_random.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_victim_sel.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/hpdcache_wbuf.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride_arb.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/hpdcache/rtl/src/hwpf_stride/hwpf_stride_wrapper.sv
/home/shc/projects/secure-soc/cva6/core/id_stage.sv
/home/shc/projects/secure-soc/cva6/core/frontend/instr_queue.sv
/home/shc/projects/secure-soc/cva6/core/instr_realign.sv
/home/shc/projects/secure-soc/cva6/core/frontend/instr_scan.sv
/home/shc/projects/secure-soc/cva6/core/include/instr_tracer_pkg.sv
/home/shc/projects/secure-soc/cva6/common/local/util/instr_tracer.sv
/home/shc/projects/secure-soc/cva6/core/issue_read_operands.sv
/home/shc/projects/secure-soc/cva6/core/issue_stage.sv
/home/shc/projects/secure-soc/cva6/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/iteration_div_sqrt_mvp.sv
/home/shc/projects/secure-soc/cva6/vendor/pulp-platform/common_cells/src/lfsr.sv
/home/shc/projects/secure-soc/cva6/vendor/pulp-platform/common_cells/src/lfsr_8bit.sv
/home/shc/projects/secure-soc/cva6/core/load_store_unit.sv
/home/shc/projects/secure-soc/cva6/core/load_unit.sv
/home/shc/projects/secure-soc/cva6/core/lsu_bypass.sv
/home/shc/projects/secure-soc/cva6/vendor/pulp-platform/common_cells/src/lzc.sv
/home/shc/projects/secure-soc/cva6/core/macro_decoder.sv
/home/shc/projects/secure-soc/rtl/src/common_cells/mem_to_banks_detailed.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/miss_handler.sv
/home/shc/projects/secure-soc/cva6/core/mult.sv
/home/shc/projects/secure-soc/cva6/core/multiplier.sv
/home/shc/projects/secure-soc/cva6/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/norm_div_sqrt_mvp.sv
/home/shc/projects/secure-soc/cva6/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/nrbd_nrsc_mvp.sv
/home/shc/projects/secure-soc/obi/src/obi_mux.sv
/home/shc/projects/secure-soc/cva6/core/perf_counters.sv
/home/shc/projects/secure-soc/register_interface/src/periph_to_reg.sv
/home/shc/projects/secure-soc/cva6/core/pmp/src/pmp.sv
/home/shc/projects/secure-soc/cva6/core/pmp/src/pmp_data_if.sv
/home/shc/projects/secure-soc/cva6/core/pmp/src/pmp_entry.sv
/home/shc/projects/secure-soc/cva6/vendor/pulp-platform/common_cells/src/popcount.sv
/home/shc/projects/secure-soc/cva6/core/cvfpu/src/fpu_div_sqrt_mvp/hdl/preprocess_mvp.sv
/home/shc/projects/secure-soc/cva6/corev_apu/rv_plic/rtl/prim_subreg.sv
/home/shc/projects/secure-soc/cva6/corev_apu/register_interface/vendor/lowrisc_opentitan/src/prim_subreg_arb.sv
/home/shc/projects/secure-soc/rtl/src/memory/prince_enc_dec.sv
/home/shc/projects/secure-soc/rtl/src/memory/ram_dwr.sv
/home/shc/projects/secure-soc/cva6/core/frontend/ras.sv
/home/shc/projects/secure-soc/register_interface/src/reg_demux.sv
/home/shc/projects/secure-soc/register_interface/src/reg_mux.sv
/home/shc/projects/secure-soc/cva6/vendor/pulp-platform/common_cells/src/rr_arb_tree.sv
/home/shc/projects/secure-soc/cva6/core/scoreboard.sv
/home/shc/projects/secure-soc/cva6/core/serdiv.sv
/home/shc/projects/secure-soc/cva6/vendor/pulp-platform/common_cells/src/shift_reg.sv
/home/shc/projects/secure-soc/rtl/src/memory/simpleuart.sv
/home/shc/projects/secure-soc/cva6/vendor/pulp-platform/common_cells/src/spill_register.sv
/home/shc/projects/secure-soc/cva6/vendor/pulp-platform/common_cells/src/spill_register_flushable.sv
/home/shc/projects/secure-soc/cva6/common/local/util/sram.sv
/home/shc/projects/secure-soc/cva6/common/local/util/sram_cache.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/std_cache_subsystem.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/std_nbdcache.sv
/home/shc/projects/secure-soc/cva6/core/store_buffer.sv
/home/shc/projects/secure-soc/cva6/core/store_unit.sv
/home/shc/projects/secure-soc/cva6/vendor/pulp-platform/common_cells/src/stream_arbiter.sv
/home/shc/projects/secure-soc/cva6/vendor/pulp-platform/common_cells/src/stream_arbiter_flushable.sv
/home/shc/projects/secure-soc/cva6/vendor/pulp-platform/common_cells/src/stream_demux.sv
/home/shc/projects/secure-soc/rtl/src/common_cells/stream_fifo.sv
/home/shc/projects/secure-soc/cva6/vendor/pulp-platform/common_cells/src/stream_fork.sv
/home/shc/projects/secure-soc/cva6/vendor/pulp-platform/common_cells/src/stream_fork_dynamic.sv
/home/shc/projects/secure-soc/cva6/vendor/pulp-platform/common_cells/src/stream_join.sv
/home/shc/projects/secure-soc/cva6/vendor/pulp-platform/common_cells/src/stream_mux.sv
/home/shc/projects/secure-soc/cva6/vendor/pulp-platform/common_cells/src/stream_register.sv
/home/shc/projects/secure-soc/cva6/vendor/pulp-platform/common_cells/src/stream_to_mem.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/tag_cmp.sv
/home/shc/projects/secure-soc/rtl/src/memory/tc_sram.sv
/home/shc/projects/secure-soc/cva6/common/local/util/tc_sram_fpga_wrapper.sv
/home/shc/projects/secure-soc/rtl/src/memory/tc_sram_wrapper_cache_techno.sv
/home/shc/projects/secure-soc/rtl/src/peripherals/timer/timer.sv
/home/shc/projects/secure-soc/rtl/src/peripherals/timer/timer_controller.sv
/home/shc/projects/secure-soc/rtl/src/peripherals/timer/timer_controller_axi.sv
/home/shc/projects/secure-soc/rtl/src/peripherals/uart/uart_controller.sv
/home/shc/projects/secure-soc/rtl/src/peripherals/uart/uart_controller_axi.sv
/home/shc/projects/secure-soc/rtl/src/peripherals/uart/uart_rx.sv
/home/shc/projects/secure-soc/rtl/src/peripherals/uart/uart_tx.sv
/home/shc/projects/secure-soc/cva6/vendor/pulp-platform/common_cells/src/unread.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/wt_axi_adapter.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/wt_cache_subsystem.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/wt_dcache.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/wt_dcache_ctrl.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/wt_dcache_mem.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/wt_dcache_missunit.sv
/home/shc/projects/secure-soc/cva6/core/cache_subsystem/wt_dcache_wbuffer.sv
/home/shc/projects/secure-soc/cva6/core/zcmt_decoder.sv
/home/shc/projects/secure-soc/rtl/src/soc/secure_soc.sv
