RISCVTYPE ?= riscv32-unknown-elf
CC = $(RISCVTYPE)-gcc

ASM = 0

# use BOOT=1 while making if you will load the program from bootloader
# e.g.
# make compile bootloader
# make compile demo BOOT=1
BOOT ?= 0

SECURE_BOOT ?= 0

WITHBOOTLOADER ?=
WITHDRAM ?=

USE_COREMARK ?= 0

ifeq ($(BOOT), 1)
    WITHBOOTLOADER := withbootloader
endif

#ifeq ($(SECURE_BOOT), 1)
##    WITHBOOTLOADER := withbootloader
## sram will use same linker
#    WITHDRAM := withdram
#endif

ifeq ($(DRAM), 1)
    WITHDRAM := withdram
endif

COMMON_PATH ?= common

LINKER_SCRIPT ?= $(COMMON_PATH)/link$(WITHBOOTLOADER)$(WITHDRAM).ld
#coremark/riscv32-baremetal/link.ld

START_ASM ?= $(COMMON_PATH)/crt0$(WITHBOOTLOADER)$(WITHDRAM).S
#coremark/riscv32-baremetal/crt0.S

DRIVERS_PATH ?= $(COMMON_PATH)/drivers
DRIVERS ?= $(DRIVERS_PATH)/uart.c $(DRIVERS_PATH)/timer.c $(DRIVERS_PATH)/qspi.c $(DRIVERS_PATH)/dram.c

ifeq ($(USE_COREMARK), 1)
	LINKER_SCRIPT := coremark/riscv32-baremetal/link$(WITHBOOTLOADER)$(WITHDRAM).ld
	START_ASM := coremark/riscv32-baremetal/crt0$(WITHBOOTLOADER)$(WITHDRAM).S
	DRIVERS += coremark/riscv32-baremetal/syscalls.c coremark/riscv32-baremetal/ee_printf.c
endif

CFILE ?= demo
CPATH ?= $(CFILE)/$(CFILE)

ifeq ($(CFILE), bootloader_dram)
#	LINKER_SCRIPT := $(COMMON_PATH)/link_asm.ld
#	START_ASM := 
	DRIVERS := $(DRIVERS_PATH)/timer.c
endif

ifeq ($(CFILE), bootloader_sram)
	DRIVERS := $(DRIVERS_PATH)/timer.c
endif

ifeq ($(CFILE), secure_bootloader_qspi)
	DRIVERS := $(DRIVERS_PATH)/timer.c $(DRIVERS_PATH)/qspi.c
endif

CFLAGS ?= -O2 -mcmodel=medany -static -std=gnu99 -fno-common -fno-unroll-loops -nostdlib -nostartfiles -fno-builtin -ffunction-sections -lm -lgcc -T $(LINKER_SCRIPT) -march=rv32im -mabi=ilp32 -I$(COMMON_PATH) -I$(DRIVERS_PATH)

ifeq ($(CFILE), simple_dram_write)
	LINKER_SCRIPT := $(COMMON_PATH)/link_asm.ld
	START_ASM := 
	DRIVERS := 
	CFLAGS := -O2 -mcmodel=medany -static -std=gnu99 -fno-common -fno-unroll-loops -nostdlib -nostartfiles -fno-builtin -ffunction-sections -lm -lgcc -T $(LINKER_SCRIPT) -march=rv32im -mabi=ilp32 -I$(COMMON_PATH) -I$(DRIVERS_PATH)
endif

ifeq ($(USE_COREMARK), 1)
	CFLAGS += -Icoremark -Icoremark/riscv32-baremetal -DITERATIONS=2000 -DUSE_COREMARK_UTILS
endif

SRCS ?= $(CPATH).c $(DRIVERS) $(START_ASM)

OUTNAME ?= $(CPATH).riscv

ifeq ($(ASM), 1)
	SRCS := $(CPATH).S
	CFLAGS := -nostartfiles -nostdlib -march=rv32im -mabi=ilp32 -T $(COMMON_PATH)/link_asm$(WITHDRAM).ld
endif

ifeq ($(SIMPLE), 1)
	DRIVERS := $(DRIVERS_PATH)/uart.c
	SRCS := $(CPATH).c $(START_ASM) $(DRIVERS)
	CFLAGS := -O0 -mcmodel=medany -static -nostartfiles -nostdlib -march=rv32im -mabi=ilp32 -T $(LINKER_SCRIPT) -I$(COMMON_PATH) -I$(DRIVERS_PATH)
endif

ifeq ($(ATOMICS), 1)
	SRCS := $(CPATH).S
	CFLAGS := -nostartfiles -nostdlib -march=rv32imac -mabi=ilp32 -T $(COMMON_PATH)/link_asm$(WITHDRAM).ld
endif

.PHONY: all
all:
	$(CC) $(CFLAGS) $(SRCS) -o $(OUTNAME)
#	$(CC) -S $(CFLAGS) $(SRCS)
#	$(CC) -c $(CFLAGS) $(SRCS)

	$(RISCVTYPE)-objdump -d -M numeric,no-aliases $(CPATH).riscv > $(CPATH).dump

	$(RISCVTYPE)-objcopy -O binary $(CPATH).riscv $(CPATH).bin
	python3 ../tools/bin2hex.py $(CPATH).bin > $(CPATH).hex

	$(RISCVTYPE)-objcopy -O verilog $(CPATH).riscv $(CPATH).vmem
	python3 ../tools/vmem_to_ddr3_init.py -i $(CPATH).vmem -o $(CPATH)_mem_init.txt

## use this for qspi flash sim
ifeq ($(BOOT), 1)
	python3 ../tools/clear_adresses_for_qspi_boot.py -f $(CPATH).vmem --place_zero > $(CPATH).tmp
	mv $(CPATH).tmp $(CPATH).vmem
endif

ifeq ($(SECURE_BOOT), 1)
#	python3 ../tools/clear_adresses_for_qspi_boot_and_encrypt.py -f $(CPATH).vmem --place_zero > $(CPATH).tmp
	python3 ../tools/clear_adresses_for_qspi_boot.py -f $(CPATH).vmem --place_zero > $(CPATH).tmp
	mv $(CPATH).tmp $(CPATH).vmem
#	python3 ../tools/encrypt_vmem.py -f $(CPATH).vmem > $(CPATH).tmp
	python3 ../tools/encrypt_vmem_aes256.py -f $(CPATH).vmem > $(CPATH).tmp
	mv $(CPATH).tmp $(CPATH)_secure.vmem
endif

ifeq ($(CFILE), bootloader)
	python3 ../tools/generate_bootrom.py -f $(CPATH).hex --addr_width 32 > ../rtl/src/memory/bootrom.sv
endif

ifeq ($(CFILE), bootloader_dram)
	python3 ../tools/generate_bootrom.py -f $(CPATH).hex --addr_width 32 > ../rtl/src/memory/bootrom.sv
endif

ifeq ($(CFILE), bootloader_sram)
	python3 ../tools/generate_bootrom.py -f $(CPATH).hex --addr_width 32 > ../rtl/src/memory/bootrom.sv
endif

ifeq ($(CFILE), secure_bootloader_qspi)
	python3 ../tools/generate_bootrom.py -f $(CPATH).hex --addr_width 32 > ../rtl/src/memory/bootrom.sv
endif

#.PHONY: $(CFILE)
#$(CFILE): all

.PHONY: clean
clean:
	rm -f $(CFILE)/*.log $(CFILE)/*.info $(CFILE)/index.html $(CFILE)/*.o $(CFILE)/*.s $(CFILE)/*.riscv $(CFILE)/*.bin $(CFILE)/*.hex $(CFILE)/*.vh $(CFILE)/*.vmem $(CFILE)/*.coe $(CFILE)/*.txt $(CFILE)/*.v $(CFILE)/*.dump $(CFILE)/*.tmp
